version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql
  app:
    image:  donnie998/dockercompose:2.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_DB_URL: jdbc:mysql://db:$DB_DOCKER_PORT/$DB_DATABASE?useSSL=false
      APP_DB_DRIVER_CLASSNAME: com.mysql.jdbc.Driver
      APP_DB_PLATFORM: "org.hibernate.dialect.MySQL5InnoDBDialect"
      APP_DB_USERNAME: $DB_USER
      APP_DB_PASSWORD: $DB_PASS
    ports:
      - 8080:8080
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80  # PHPMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
volumes:
  db: