version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql
  app:
    image: donnie998/dockercompose:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:1521/mydb
      SPRING_DATASOURCE_USERNAME: my_username
      SPRING_DATASOURCE_PASSWORD: my_password
      SERVER_PORT: 8080
    ports:
      - 8080:8080
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80  # PHPMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
volumes:
  db: